# Attention Mechanism

Self attention allows each position in the input sequence to consider the relevancy of all the other positions in the same sequence when computing the representation of a sequence

## Simplified Attention

In [4]:
import torch


In [5]:
inputs = torch.tensor(
    [
        [0.43, 0.15, 0.89],
        [0.55, 0.87, 0.66],
        [0.57, 0.85, 0.64],
        [0.22, 0.58, 0.33],
        [0.77, 0.25, 0.10],
        [0.05, 0.80, 0.55]
    ]
)

### Step 1: Calculate attention scores

In [16]:
query = inputs[1]
attn_scores_2 = torch.empty(inputs.shape[0])

for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query) #calculate the dot product of every position with x_i

print(attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


Dot product measures how similar vectors are i.e. higher dot product == closer vectors 

### Step 2: Normalization

TThe dot product between the queries and keys produces scores that show the relationship between them. They are unnormalised and can span any range of values. This is important so as to maintain training stability in an LLM by obtaining attention weights that sum up to 1. This is done to transform the scores into a set of usable weights that represent a distribution of attention.

In [22]:
attn_weights_2_tmp = attn_scores_2/ attn_scores_2.sum()
print('Attention weights:', attn_weights_2_tmp)
print('Sum:', attn_weights_2_tmp.sum())

Attention weights: tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
Sum: tensor(1.0000)


Use the softmax in practise. It makes sure that attention weights are always positive. It is better at managing extreme values and offers more favorable gradient properties during training

In [31]:

attn_weights_2 = softmax(attn_scores_2)
print('Attention weights:', attn_weights_2)
print('Sum:', attn_weights_2.sum())

Attention weights: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum: tensor(1.)


In [32]:
context_vec_2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    context_vec_2 += attn_weights_2[i] *x_i

print(context_vec_2)

tensor([0.4419, 0.6515, 0.5683])


In [33]:
attn_scores = torch.empty(6,6)
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i, j] = torch.dot(x_i, x_j)

print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [34]:
attn_scores = input @ inputs.T

TypeError: unsupported operand type(s) for @: 'method' and 'Tensor'